### PR TITLE
Switch license to MIT/Apache2 instead of Unlicense

### PR DESCRIPTION
**Pull request by nikomatsakis**
I've decided I might as well adopt the usual Rust license convention, which is to have both a MIT/Apache2 license. This is partly in response to the various legal criticisms of the Unlicense floating around as well as a general desire to keep things uniform for users (it's easier on everyone if there are fewer licenses to contend with).

Most of the code in LALRPOP is still my work, but here is a list of other authors generated by git. If you are ok with me re-licensing your contributions, can you indicate that? Thanks!

- [x] Niko Matsakis @nikomatsakis
- [x] Ahmed Charles @ahmedcharles 
- [x] Brian Anderson @brson 
- [x] Florian Hahn @fhahn 
- [x] Jason Dagit @dagit 
- [x] Jonas Schievink @jonas-schievink 
- [ ] Joshua Bell @pensivearchitect 
- [x] Sebastian Hahn @shahn 
- [x] Will Crichton @willcrichton 
- [x] Yehuda Katz @wycats

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Sure, why not?

**Comment by shahn** [comment]
Sounds good to me. Dunno I've contributed anything substantial anyway

**Comment by ahmedcharles** [comment]
I'm fine with this.

**Comment by fhahn** [comment]
I am fine with that as well

**Comment by brson** [comment]
My contributions to lalrpop can be licensed mit/apache2.

**Comment by dagit** [comment]
I'm okay with my changes being MIT/apache2 licensed.

**Comment by willcrichton** [comment]
Works for me.

**Comment by nikomatsakis** [comment]
OK, I'm going to go ahead and make the change. 

@pensivearchitect hasn't responded yet, but reviewing the commit logs it seems that they only corrected a few typos (not to diminish the importance of fixing typos! :smile:) so I think that doesn't really qualify for copyright anyhow.

Thanks everyone for responding, sorry for disturbing you.

**Pull request merged**
