### PR TITLE
unify dep info

### PR DESCRIPTION
**Pull request by king6cong**
cargo test --all can be eventually used for
the whole workspace testing after all doctests
pass.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm, there is a script that is supposed to be keeping these in sync. It's probably missing some entries.

**Comment by king6cong** [comment]
Thanks, I looked into it.

* publish.sh regex failed to match version info like this { version = "0.12.0", path = "../../lalrpop-util" }
* doc/whitespace/Cargo.toml use lalrpop = "0.12.5" directly so duplicate dep files are generated.
* git add -f to make sure .gitignore files do not get in our way.

**Comment by king6cong** [comment]
And cargo test --all fails for some doc tests, but we can leave it for another PR 😄

**Comment by nikomatsakis** [comment]
@king6cong thanks for looking into that! think you can fix the script?

**Comment by ahmedcharles** [comment]
I fixed the doctests, though `cargo test --all` still fails due to the reasons fixed by this change.

You'll have to rebase past one of my changes though, unfortunately, because it changes a Cargo.toml. Sorry. :)

**Comment by king6cong** [comment]
@nikomatsakis PR already updated. Including changes to the script.

**Comment by king6cong** [comment]
@ahmedcharles Thanks! I'am out on a trip and resolved conflict on my phone. Please help me review it

**Comment by nikomatsakis** [comment]
@king6cong it seems fine to me, but can you rebase so as to eliminate the 'merge' commit?

**Comment by king6cong** [comment]
@nikomatsakis Yeah，I will do it as soon as I'm back with a computer 😃

**Comment by king6cong** [comment]
@nikomatsakis PR updated.

**Comment by nikomatsakis** [comment]
Thanks =)

**Pull request merged**
